import { Restaurant } from '../types/restaurant';

export const mockRestaurants: Restaurant[] = [
  {
    id: '1',
    name: '鼎泰豐',
    address: '台北市大安區信義路二段194號',
    latitude: 25.0330,
    longitude: 121.5297,
    rating: 4.5,
    priceLevel: 3,
    cuisineType: '台式料理',
    distance: 500,
    imageUrl: 'https://picsum.photos/400/300?random=1',
    isBlacklisted: false,
    isFavorite: true,
  },
  {
    id: '2',
    name: '欣葉日本料理',
    address: '台北市信義區松高路11號',
    latitude: 25.0356,
    longitude: 121.5687,
    rating: 4.3,
    priceLevel: 4,
    cuisineType: '日式料理',
    distance: 1200,
    imageUrl: 'https://picsum.photos/400/300?random=2',
    isBlacklisted: false,
    isFavorite: false,
  },
  {
    id: '3',
    name: '阿宗麵線',
    address: '台北市萬華區峨眉街8-1號',
    latitude: 25.0425,
    longitude: 121.5063,
    rating: 4.1,
    priceLevel: 1,
    cuisineType: '小吃',
    distance: 800,
    imageUrl: 'https://picsum.photos/400/300?random=3',
    isBlacklisted: false,
    isFavorite: false,
  },
  {
    id: '4',
    name: '金峰魯肉飯',
    address: '台北市中正區羅斯福路一段10號',
    latitude: 25.0175,
    longitude: 121.5230,
    rating: 4.2,
    priceLevel: 1,
    cuisineType: '小吃',
    distance: 600,
    imageUrl: 'https://picsum.photos/400/300?random=4',
    isBlacklisted: false,
    isFavorite: true,
  },
  {
    id: '5',
    name: 'RAW',
    address: '台北市中山區樂群三路301號',
    latitude: 25.0797,
    longitude: 121.5569,
    rating: 4.8,
    priceLevel: 4,
    cuisineType: '創意料理',
    distance: 2500,
    imageUrl: 'https://picsum.photos/400/300?random=5',
    isBlacklisted: false,
    isFavorite: false,
  },
];

export const cuisineTypes = [
  '台式料理',
  '日式料理',
  '韓式料理',
  '義式料理',
  '美式料理',
  '小吃',
  '創意料理',
  '中式料理',
  '泰式料理',
  '法式料理',
];